% Practice with the MATLAB problems from DSP book

Fs = 1000;
Nf = Fs/2;
n = 7;

pf = [150 250];
pf = pf/Nf;

%d = designfilt('PassbandFrequency1',pf(1), 'PassbandFrequency2', pf(2), ...
%         'PassbandRipple',0.1, ...
%         'TransitionWidth', 0.2, ...
%         'StopbandAttenuation',60,'DesignMethod','hamming');
d = designfilt('bandpassfir', 'StopbandFrequency1', 0.35, ...
               'PassbandFrequency1', pf(1), 'PassbandFrequency2', ...
               pf(2), 'StopbandFrequency2', 0.65, ...
               'StopbandAttenuation1', 60, 'PassbandRipple', 0.1, ...
               'StopbandAttenuation2', 60, 'DesignMethod', 'equiripple');
fvtool(d);


